# 配置本服务端口号
server:
  port: 1448

# 配置数据库连接信息
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource # 连接池类型
    driver-class-name: com.mysql.cj.jdbc.Driver # 驱动名称
    url: jdbc:mysql://localhost:3306/db_spzx?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: 1448381936yckYCK
  # Redis的相关配置
  data:
    redis:
      host: localhost
      port: 6379
#      password: 1448381936yckYCK

# mybatis的配置
mybatis:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:/mapper/*/*.xml

# 自定义配置
spzx:
  auth:
    noAuthUrls:
      - /admin/system/index/login
      - /admin/system/index/generateValidateCode
      - /swagger-resources/**
      - /doc.html
      - /webjars/**
      - /swagger-ui/**
      - /*/api-docs/**
  minio:
    endpointUrl: http://127.0.0.1:9090
    accessKey: yogi
    secreKey: 1448381936yckYCK
    bucketName: spzx-bucket
