# 配置本服务端口号
server:
  port: 1448

# 配置数据库连接信息
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource # 连接池类型
    driver-class-name: com.mysql.cj.jdbc.Driver # 驱动名称
    url: jdbc:mysql://121.41.52.4:3306/db_spzx?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: 1448381936yckYCK
  # Redis的相关配置
  data:
    redis:
      host: 121.41.52.4
      port: 6379
      password: 1448381936yckYCK

# mybatis的配置
mybatis:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:/mapper/*/*.xml

# 自定义配置
spzx:
  auth:
    noAuthUrls:
      - /admin/index/login
      - /admin/index/captcha
      - /swagger-resources/**
      - /doc.html
      - /webjars/**
      - /swagger-ui/**
      - /*/api-docs/**
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    bucketName: spzx-bucket-yck
    accessKeyID: LTAI5tBsrrPtTfr6E8SkTqf2
    accessKey: uJnWqv6G6Bj2svCPRU78rekDYCiCCJ