server:
  port: 1451

spring:
  application:
    name: service-user
  cloud:
    nacos:
      discovery:
        ip: 120.27.201.144
        port: 1451
        server-addr: 121.41.52.4:8848
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.41.52.4:3306/db_spzx?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: 1448381936yckYCK
  # Redis的相关配置
  data:
    redis:
      host: 121.41.52.4
      port: 6379
      password: 1448381936yckYCK

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*/*.xml

# 第三方短信验证码服务 三网106短信
sms:
  host: https://gyytz.market.alicloudapi.com
  path: /sms/smsSend
  method: POST
  appcode: bc6ab584b10440a8926cfaece52583b5
  sms-sign-id: 2e65b1bb3d054466b82f0c9d125465e2
  template-id: 908e94ccf08b4476ba6c876d13f084ad
