server:
  port: 1453

spring:
  application:
    name: service-cart
  cloud:
    nacos:
      discovery:
        server-addr: 121.41.52.4:8848
  data:
    redis:
      host: 121.41.52.4
      port: 6379
      password: 1448381936yckYCK